
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tp_music?serverTimezone=Asia/Shanghai
    username: root
    password: li1234567
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: test
server:
  port: 8888